declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_GITHUB_TOKEN: string
    NEXT_PUBLIC_GITHUB_USERNAME: string
    NEXT_PUBLIC_LINKEDIN_USERNAME: string
    NEXT_PUBLIC_MEDIUM_USERNAME: string
    NEXT_PUBLIC_PROFILE_DATA_URL: string
    NEXT_PUBLIC_METADATA_TITLE: string
    NEXT_PUBLIC_METADATA_DESCRIPTION: string
    NEXT_PUBLIC_FEATURED_PROJECTS: string
  }
}
